#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean
wclean interDyMFoam
wclean MRFInterFoam
wclean porousInterFoam
wclean LTSInterFoam
wclean interMixingFoam

# ----------------------------------------------------------------- end-of-file
