#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso viscosityModels
wmake libso relativeVelocityModels
wmake

# ----------------------------------------------------------------- end-of-file
